from __future__ import annotations

from typing import Protocol

from chattergpt.models import BackendStatus, ConversationData, ConversationSummary, StreamEvent


class ChatBackend(Protocol):
    async def start(self) -> BackendStatus: ...

    async def close(self) -> None: ...

    async def check_auth(self) -> BackendStatus: ...

    async def refresh_conversations(self) -> list[ConversationSummary]: ...

    async def open_conversation(self, remote_id: str | None) -> ConversationData: ...

    async def send_message(self, remote_id: str | None, prompt: str) -> list[StreamEvent]: ...

    async def reveal_browser(self) -> BackendStatus: ...
